create table
  public.global_inventory (
    id bigint generated by default as identity,
    num_red_ml integer null,
    gold integer null,
    num_blue_ml integer null,
    num_green_ml integer null,
    num_dark_ml integer null,
    constraint global_inventory_pkey primary key (id)
  ) tablespace pg_default;

create table
  public.potions (
    id bigint generated by default as identity,
    sku text not null,
    name text null,
    quantity integer null,
    price integer null,
    red_ml integer null,
    green_ml integer null,
    blue_ml integer null,
    dark_ml integer null,
    constraint potions_pkey primary key (id),
    constraint potions_quantity_check check ((quantity >= 0))
  ) tablespace pg_default;

create table
  public.carts (
    id bigint generated by default as identity,
    customer text not null,
    total_price integer null,
    constraint carts_pkey primary key (id)
  ) tablespace pg_default;

create table
  public.cart_items (
    id bigint generated by default as identity,
    item_key bigint not null,
    quantity integer null,
    cart_id bigint not null,
    constraint cart_items_pkey primary key (id),
    constraint cart_items_cart_id_fkey foreign key (cart_id) references carts (id) on delete cascade,
    constraint cart_items_item_key_fkey foreign key (item_key) references potions (id)
  ) tablespace pg_default;

create table
  public.inventory_transactions (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    customer text null,
    gold_change integer null,
    red_ml_change integer null,
    green_ml_change integer null,
    blue_ml_change integer null,
    dark_ml_change integer null,
    constraint cart_transactions_pkey primary key (id)
  ) tablespace pg_default;

create table
  public.potion_transactions (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    customer text null,
    potion_id bigint null,
    potion_quantity_change integer null,
    constraint potion_transactions_pkey primary key (id),
    constraint potion_transactions_potion_id_fkey foreign key (potion_id) references potions (id)
  ) tablespace pg_default;